name: ci
  
on:
  push:

jobs:
  build-docker-archive:
    runs-on: ubuntu-latest
    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000
    steps:
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          # list of Docker images to use as base name for tags
          images: |
            name/app
            ghcr.io/username/app            
          # generate Docker tags based on the following events/attributes
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha 

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: network=host
      
      - name: Build
        uses: docker/build-push-action@v6
        with:
          load: true
          push: true
          tags: localhost:5000/myimage:latest

      - name: Create Tgz|Manifest|SHA
        # This would actually build your project, using zip for an example artifact
        run: |
          docker pull localhost:5000/myimage:latest
          docker image list
          contid=$(docker create localhost:5000/myimage:latest)
          docker export $contid | gzip > out.tar.gz
          sha256sum out.tar.gz | tee out.sha256

      - name: Release
        uses: softprops/action-gh-release@v2
        
        #if: startsWith(github.ref, 'refs/tags/')
        with:
          fail_on_unmatched_files: true
          tag_name: 0.0.1
          files: |
            out.tar.gz
            out.sha256
